name: Image Build

inputs: 
  registry_project_id:
    required: true
    type: string
  env:
    required: true
    type: string
  region:
    required: true
    type: string
  repository:
    required: true
    type: string
  image: 
  dockerfile:
  build_args:
  
