name: Build and Push Docker Image to GCP Artifact Registry

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'

env:
  PROJECT_ID: "gcppracticedemo-467805"
  GAR_LOCATION: "us-central1"
  REPOSITORY_NAME: "gcp-demo-project-docker-repository"
  IMAGE_NAME: "gcp-fastapi-application"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
 
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/369637014080/locations/global/workloadIdentityPools/github-pool/providers/github-provider"
          service_account: "gcppracticedemo-467805@gcppracticedemo-467805.iam.gserviceaccount.com"

      - name: 'Configure Docker'
        run: 'gcloud auth configure-docker ${{ env.GAR_LOCATION }}-docker.pkg.dev'

      - name: 'Build Docker image'
        run: |
          docker build -t ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY_NAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }} \
                       -t ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY_NAME }}/${{ env.IMAGE_NAME }}:latest ./src

      - name: 'Push Docker image (SHA tag)'
        run: |
          docker push ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY_NAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: 'Push Docker image (latest tag)'
        run: |
          docker push ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY_NAME }}/${{ env.IMAGE_NAME }}:latest