name: Terraform Plan

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  id-token: write


jobs:
  terraform_plan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/369637014080/locations/global/workloadIdentityPools/github-pool/providers/github-provider"
          service_account: "gcppracticedemo-467805@gcppracticedemo-467805.iam.gserviceaccount.com"

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.0.0 # Specify your desired Terraform version

      - name: Terraform Init
        id: init
        run: terraform init -backend-config="bucket=gcpproject-terraform-bucket"
        working-directory: ./terraform

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
        working-directory: ./terraform