name: Terraform Plan

on:
  pull_request:
    branches:
      - main

jobs:
  terraform_plan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.0.0 # Specify your desired Terraform version

      - name: Terraform Init
        id: init
        run: terraform init -backend-config="bucket=Gcpproject-terraform-bucket"
        working-directory: ./terraform

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
        working-directory: ./terraform
        continue-on-error: true

      - name: Add Plan to PR
        uses: actions/github-script@v6
        if: github.event_name == 'pull_request'
                   script: |
            const output = `#### Terraform Plan\n\n<details><summary>Show Plan</summary>\n\n```terraform\n${process.env.TF_PLAN}\n```\n\n</details>\n\n*Pushed by: @${github.actor}, Action: \n<https://github.com/${github.repository}/actions/runs/${github.run_id}>*\n`;n';
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })        env:
          TF_PLAN: ${{ steps.plan.outputs.stdout }}