name: Terraform Plan

on:
  pull_request:
    branches:
      - main

jobs:
  terraform_plan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.0.0 # Specify your desired Terraform version

      - name: Terraform Init
        id: init
        run: terraform init -backend-config="bucket=Gcpproject-terraform-bucket"
        working-directory: ./terraform

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
        working-directory: ./terraform