name: Security Scan for Terraform Infrastructure 

on:
  pull_request:
    branches: [ "main" ]

permissions:
    actions: read
    contents: read
    security-events: write

jobs:
  tfsec:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - name: Run tfsec
        uses: aquasecurity/tfsec-sarif-action@21ded20e8ca120cd9d3d6ab04ef746477542a608
        with:
          sarif_file: tfsec.sarif
          working_directory: ./terraform 

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: tfsec.sarif